name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk wget

    - name: Set up Android SDK
      run: |
        # Accept licenses
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Update SDK tools and accept licenses
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required SDK components
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;25b"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Verify buildozer.spec
      run: |
        echo "=== buildozer.spec ==="
        cat buildozer.spec
        echo "\n===================="

    - name: Build with Buildozer
      run: |
        # Set environment variables
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25b
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # Run buildozer with debug info
        buildozer -v android debug
        
        # List the built APK
        ls -la bin/

    - name: List build artifacts
      run: |
        ls -la bin/

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: taki-poker-apk
        path: bin/*.apk
        retention-days: 7
        if-no-files-found: error

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
